services:
  multiroom-audio:
    build: .
    image: ghcr.io/rnestler/docker-multiroom-audio:main
    hostname: multiroom-audio
    user: "${USER_ID:?}:${GROUP_ID:?}"
    networks:
      multiroom:
        ipv4_address: ${CONTAINER_IP:?}
    volumes:
      - ./snapserver.conf:/etc/snapserver.conf:ro
      - ./mpd:/var/lib/mpd
      - ./snapserver:/var/lib/snapserver
      - ./librespot-cache:/var/lib/librespot-cache
      - ./mympd:/var/lib/mympd

networks:
  multiroom:
    driver: ipvlan
    driver_opts:
      parent: ${NETWORK_INTERFACE:?}
    ipam:
      config:
        - subnet: ${SUBNET:?}
          gateway: ${GATEWAY:?}
          ip_range: ${IP_RANGE:?}
