bind_to_address "0.0.0.0"
port "6600"

music_directory    "/var/lib/mpd/music"
playlist_directory "/var/lib/mpd/playlists"
db_file            "/var/lib/mpd/data/database"
state_file         "/var/lib/mpd/data/state"
sticker_file       "/var/lib/mpd/data/sticker.sql"

log_file "syslog"

audio_output {
    type       "fifo"
    name       "snapserver"
    path       "/tmp/snapfifo-mpd"
    format     "44100:16:2"
    mixer_type "software"
}
