[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:snapserver]
command=snapserver -c /etc/snapserver.conf --server.datadir=/var/lib/snapserver
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
autorestart=true

[program:mpd]
command=mpd --stdout --no-daemon /etc/mpd.conf
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
autorestart=true

[program:mympd]
command=mympd -w /var/lib/mympd -a /var/cache/mympd
environment=MYMPD_HTTP=true,MYMPD_SSL=false
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
autorestart=true
